/**
 * CoverArtDimensionsPanel
 *
 * Displays the auto-inferred cover art dimensions (15-dimension framework)
 * and synthesis fingerprint for a track. Shows what the system inferred about
 * the music's visual character.
 *
 * Dimensions: 5 Energy, 5 Emotion, 5 Culture
 */

import { useState } from "react";
import { ChevronDown, ChevronUp, Sparkles, Copy, Check } from "lucide-react";
import { Button } from "@/components/ui/button";
import { cn } from "@/lib/utils";

export interface DimensionAnswers {
  energyDirection: string;
  energyShape: string;
  energyTexture: string;
  energyWeight: string;
  energyPace: string;
  emotionStance: string;
  emotionResolution: string;
  emotionIntensity: string;
  emotionTone: string;
  emotionMovement: string;
  culturePosition: string;
  cultureAuthenticity: string;
  cultureDensity: string;
  cultureTemporality: string;
  cultureReference: string;
  confidenceScores?: Record<string, number>;
  synthesisFingerprint?: string;
}

interface CoverArtDimensionsPanelProps {
  dimensionsJson: string | null | undefined;
  className?: string;
}

function parseDimensions(json: string | null | undefined): DimensionAnswers | null {
  if (!json) return null;
  try {
    return JSON.parse(json) as DimensionAnswers;
  } catch {
    return null;
  }
}

function formatDimensionsForCopy(dims: DimensionAnswers, title?: string): string {
  const lines = [
    title ? `🎨 COVER ART DIMENSIONS — ${title}` : "🎨 COVER ART DIMENSIONS",
    "",
    "✨ SYNTHESIS FINGERPRINT",
    dims.synthesisFingerprint || "No description available",
    "",
    "⚡ ENERGY (5 dimensions)",
    `  • Direction: ${dims.energyDirection}`,
    `  • Shape: ${dims.energyShape}`,
    `  • Texture: ${dims.energyTexture}`,
    `  • Weight: ${dims.energyWeight}`,
    `  • Pace: ${dims.energyPace}`,
    "",
    "❤️ EMOTION (5 dimensions)",
    `  • Stance: ${dims.emotionStance}`,
    `  • Resolution: ${dims.emotionResolution}`,
    `  • Intensity: ${dims.emotionIntensity}`,
    `  • Tone: ${dims.emotionTone}`,
    `  • Movement: ${dims.emotionMovement}`,
    "",
    "🌍 CULTURE (5 dimensions)",
    `  • Position: ${dims.culturePosition}`,
    `  • Authenticity: ${dims.cultureAuthenticity}`,
    `  • Density: ${dims.cultureDensity}`,
    `  • Temporality: ${dims.cultureTemporality}`,
    `  • Reference: ${dims.cultureReference}`,
    "",
    "— Generated by Strawberry Riff Cover Art Inference Engine",
  ];
  return lines.join("\n");
}

export function CoverArtDimensionsPanel({ dimensionsJson, className }: CoverArtDimensionsPanelProps) {
  const [isOpen, setIsOpen] = useState(false);
  const [copied, setCopied] = useState(false);

  const dims = parseDimensions(dimensionsJson);
  if (!dims) return null;

  const handleCopy = async () => {
    try {
      await navigator.clipboard.writeText(formatDimensionsForCopy(dims));
      setCopied(true);
      setTimeout(() => setCopied(false), 2000);
    } catch {
      // Fallback for older browsers
      const el = document.createElement("textarea");
      el.value = formatDimensionsForCopy(dims);
      document.body.appendChild(el);
      el.select();
      document.execCommand("copy");
      document.body.removeChild(el);
      setCopied(true);
      setTimeout(() => setCopied(false), 2000);
    }
  };

  return (
    <div
      className={cn(
        "rounded-2xl border overflow-hidden transition-all bg-gradient-to-br from-purple-50 to-pink-50 border-purple-100",
        className
      )}
    >
      {/* Header — always visible */}
      <div
        role="button"
        tabIndex={0}
        onClick={() => setIsOpen((o) => !o)}
        onKeyDown={(e) => {
          if (e.key === "Enter" || e.key === " ") setIsOpen((o) => !o);
        }}
        className="w-full flex items-center justify-between px-5 py-4 hover:bg-white/50 transition-colors group cursor-pointer"
      >
        <div className="flex items-center gap-3">
          <Sparkles className="w-5 h-5 text-purple-600 flex-shrink-0" />
          <div className="flex-1 min-w-0">
            <span className="text-sm font-semibold text-foreground">What the system inferred</span>
            <p className="text-xs text-gray-700 mt-0.5 line-clamp-2">
              {dims.synthesisFingerprint}
            </p>
          </div>
        </div>
        <div className="flex items-center gap-2 flex-shrink-0">
          <Button
            size="sm"
            variant="ghost"
            onClick={(e) => {
              e.stopPropagation();
              handleCopy();
            }}
            className="h-8 px-2.5 text-xs text-muted-foreground hover:text-foreground hover:bg-white gap-1.5"
          >
            {copied ? (
              <>
                <Check className="w-3.5 h-3.5 text-green-600" />
                <span className="hidden sm:inline">Copied</span>
              </>
            ) : (
              <>
                <Copy className="w-3.5 h-3.5" />
                <span className="hidden sm:inline">Copy</span>
              </>
            )}
          </Button>
          {isOpen ? (
            <ChevronUp className="w-4 h-4 text-muted-foreground group-hover:text-foreground transition-colors flex-shrink-0" />
          ) : (
            <ChevronDown className="w-4 h-4 text-muted-foreground group-hover:text-foreground transition-colors flex-shrink-0" />
          )}
        </div>
      </div>

      {/* Expanded content */}
      {isOpen && (
        <div className="px-5 pb-5 space-y-4 border-t border-purple-100 pt-4">
          {/* Synthesis Fingerprint — full width highlight */}
          <div className="bg-white/60 border border-purple-200/50 rounded-xl px-4 py-3.5">
            <div className="flex items-center gap-2 mb-2">
              <Sparkles className="w-4 h-4 text-purple-600" />
              <span className="text-xs font-semibold text-purple-700 uppercase tracking-wide">
                Synthesis Fingerprint
              </span>
            </div>
            <p className="text-sm text-foreground leading-relaxed">
              {dims.synthesisFingerprint}
            </p>
          </div>

          {/* Three-column grid for dimension groups */}
          <div className="grid grid-cols-1 sm:grid-cols-3 gap-3">
            {/* Energy */}
            <DimensionGroup
              title="⚡ Energy"
              color="purple"
              items={[
                { label: "Direction", value: dims.energyDirection },
                { label: "Shape", value: dims.energyShape },
                { label: "Texture", value: dims.energyTexture },
                { label: "Weight", value: dims.energyWeight },
                { label: "Pace", value: dims.energyPace },
              ]}
              scores={dims.confidenceScores}
            />

            {/* Emotion */}
            <DimensionGroup
              title="❤️ Emotion"
              color="pink"
              items={[
                { label: "Stance", value: dims.emotionStance },
                { label: "Resolution", value: dims.emotionResolution },
                { label: "Intensity", value: dims.emotionIntensity },
                { label: "Tone", value: dims.emotionTone },
                { label: "Movement", value: dims.emotionMovement },
              ]}
              scores={dims.confidenceScores}
            />

            {/* Culture */}
            <DimensionGroup
              title="🌍 Culture"
              color="blue"
              items={[
                { label: "Position", value: dims.culturePosition },
                { label: "Authenticity", value: dims.cultureAuthenticity },
                { label: "Density", value: dims.cultureDensity },
                { label: "Temporality", value: dims.cultureTemporality },
                { label: "Reference", value: dims.cultureReference },
              ]}
              scores={dims.confidenceScores}
            />
          </div>

          {/* Footer hint */}
          <p className="text-xs text-gray-700 text-center pt-1">
            15-dimension framework • Auto-inferred when track was published
          </p>
        </div>
      )}
    </div>
  );
}

function DimensionGroup({
  title,
  color,
  items,
  scores,
}: {
  title: string;
  color: "purple" | "pink" | "blue";
  items: Array<{ label: string; value: string }>;
  scores?: Record<string, number>;
}) {
  const bgMap = {
    purple: "bg-purple-50 border-purple-100",
    pink: "bg-pink-50 border-pink-100",
    blue: "bg-blue-50 border-blue-100",
  };
  const labelMap = {
    purple: "text-purple-700",
    pink: "text-pink-700",
    blue: "text-blue-700",
  };

  return (
    <div className={cn("rounded-lg border p-3 space-y-2.5", bgMap[color])}>
      <h4 className={cn("text-xs font-semibold uppercase tracking-wide", labelMap[color])}>
        {title}
      </h4>
      <div className="space-y-1.5">
        {items.map((item) => {
          const scoreKey = item.label.toLowerCase().replace(/\s+/g, "");
          const score = scores?.[scoreKey] ?? scores?.[item.label.toLowerCase()] ?? null;
          return (
            <div key={item.label} className="flex items-start justify-between gap-2">
              <span className="text-xs text-gray-900 font-medium">{item.label}</span>
              <div className="flex items-center gap-1.5">
                <span className="text-xs font-medium text-gray-900 text-right capitalize">
                  {item.value}
                </span>
                {score !== null && (
                  <div className="w-6 h-4 bg-white rounded-sm border border-gray-300 flex items-center justify-center">
                    <span className="text-[10px] font-semibold text-gray-900">
                      {Math.round(score * 100)}%
                    </span>
                  </div>
                )}
              </div>
            </div>
          );
        })}
      </div>
    </div>
  );
}
