/**
 * VisualBriefPanel
 *
 * Displays an auto-generated cinematic visual brief for a completed music
 * generation. Derived from the Music + Visual Stickiness Master Formula
 * (Chapter 9 of the Strawberry Riff Music Prompt Bible).
 *
 * Designed to be portable — users can copy the full brief and paste it
 * into Runway, Kling, Sora, or any other video generation tool.
 */

import { useState } from "react";
import { ChevronDown, ChevronUp, Camera, Lightbulb, Palette, Smile, MapPin, Clapperboard, Copy, Check, Zap } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Badge } from "@/components/ui/badge";
import { cn } from "@/lib/utils";

export interface VisualBrief {
  camera: string;
  lighting: string;
  colorPalette: string[];
  emotionArc: string;
  scene: string;
  directorNote: string;
  pacing: string;
}

interface VisualBriefPanelProps {
  visualBriefJson: string | null | undefined;
  /** If true, renders in a dark-on-dark style (for use inside Studio dark themes) */
  darkMode?: boolean;
  className?: string;
}

const PACING_COLORS: Record<string, string> = {
  "slow burn": "bg-blue-900/60 text-blue-200 border-blue-700/50",
  "mid-tempo": "bg-purple-900/60 text-purple-200 border-purple-700/50",
  "rapid-cut": "bg-red-900/60 text-red-200 border-red-700/50",
  "pulse-sync": "bg-pink-900/60 text-pink-200 border-pink-700/50",
  "freeform": "bg-teal-900/60 text-teal-200 border-teal-700/50",
};

function parseBrief(json: string | null | undefined): VisualBrief | null {
  if (!json) return null;
  try {
    return JSON.parse(json) as VisualBrief;
  } catch {
    return null;
  }
}

function formatBriefForCopy(brief: VisualBrief, title?: string): string {
  return [
    title ? `🎬 VISUAL BRIEF — ${title}` : "🎬 VISUAL BRIEF",
    "",
    `📽 DIRECTOR'S NOTE`,
    brief.directorNote,
    "",
    `🎥 CAMERA`,
    brief.camera,
    "",
    `💡 LIGHTING`,
    brief.lighting,
    "",
    `🎨 COLOR PALETTE`,
    brief.colorPalette.join(" · "),
    "",
    `😊 EMOTION ARC`,
    brief.emotionArc,
    "",
    `🎭 SCENE`,
    brief.scene,
    "",
    `⚡ PACING: ${brief.pacing.toUpperCase()}`,
    "",
    "— Generated by Strawberry Riff Visual Brief Generator",
  ].join("\n");
}

export function VisualBriefPanel({ visualBriefJson, darkMode = false, className }: VisualBriefPanelProps) {
  const [isOpen, setIsOpen] = useState(false);
  const [copied, setCopied] = useState(false);

  const brief = parseBrief(visualBriefJson);
  if (!brief) return null;

  const pacingClass = PACING_COLORS[brief.pacing.toLowerCase()] ?? "bg-gray-800/60 text-gray-300 border-gray-600/50";

  const handleCopy = async () => {
    try {
      await navigator.clipboard.writeText(formatBriefForCopy(brief));
      setCopied(true);
      setTimeout(() => setCopied(false), 2000);
    } catch {
      // Fallback for older browsers
      const el = document.createElement("textarea");
      el.value = formatBriefForCopy(brief);
      document.body.appendChild(el);
      el.select();
      document.execCommand("copy");
      document.body.removeChild(el);
      setCopied(true);
      setTimeout(() => setCopied(false), 2000);
    }
  };

  return (
    <div
      className={cn(
        "rounded-lg border overflow-hidden transition-all",
        darkMode
          ? "bg-black/30 border-white/10"
          : "bg-slate-900/95 border-slate-700/60",
        className
      )}
    >
      {/* Header — always visible */}
      <button
        onClick={() => setIsOpen((o) => !o)}
        className="w-full flex items-center justify-between px-4 py-3 hover:bg-white/5 transition-colors group"
      >
        <div className="flex items-center gap-2.5">
          <Clapperboard className="w-4 h-4 text-pink-400 flex-shrink-0" />
          <span className="text-sm font-semibold text-white">Visual Brief</span>
          <Badge
            variant="outline"
            className={cn("text-[10px] px-1.5 py-0 border font-medium", pacingClass)}
          >
            {brief.pacing}
          </Badge>
          <span className="text-xs text-slate-400 italic hidden sm:inline truncate max-w-[200px]">
            {brief.directorNote}
          </span>
        </div>
        <div className="flex items-center gap-2">
          <Button
            size="sm"
            variant="ghost"
            onClick={(e) => { e.stopPropagation(); handleCopy(); }}
            className="h-7 px-2 text-xs text-slate-400 hover:text-white hover:bg-white/10 gap-1"
          >
            {copied ? (
              <><Check className="w-3 h-3 text-green-400" /> Copied</>
            ) : (
              <><Copy className="w-3 h-3" /> Copy</>
            )}
          </Button>
          {isOpen
            ? <ChevronUp className="w-4 h-4 text-slate-400 group-hover:text-white transition-colors flex-shrink-0" />
            : <ChevronDown className="w-4 h-4 text-slate-400 group-hover:text-white transition-colors flex-shrink-0" />
          }
        </div>
      </button>

      {/* Expanded content */}
      {isOpen && (
        <div className="px-4 pb-4 space-y-3 border-t border-white/10 pt-3">
          {/* Director's Note — full width highlight */}
          <div className="bg-pink-950/40 border border-pink-800/30 rounded-md px-3 py-2.5">
            <div className="flex items-center gap-1.5 mb-1">
              <Clapperboard className="w-3.5 h-3.5 text-pink-400" />
              <span className="text-[11px] font-semibold text-pink-300 uppercase tracking-wider">Director's Note</span>
            </div>
            <p className="text-sm text-white leading-relaxed">{brief.directorNote}</p>
          </div>

          {/* Two-column grid for the main fields */}
          <div className="grid grid-cols-1 sm:grid-cols-2 gap-2.5">
            <BriefField icon={<Camera className="w-3.5 h-3.5 text-sky-400" />} label="Camera" color="sky" value={brief.camera} />
            <BriefField icon={<Lightbulb className="w-3.5 h-3.5 text-amber-400" />} label="Lighting" color="amber" value={brief.lighting} />
            <BriefField icon={<Smile className="w-3.5 h-3.5 text-violet-400" />} label="Emotion Arc" color="violet" value={brief.emotionArc} />
            <BriefField icon={<MapPin className="w-3.5 h-3.5 text-emerald-400" />} label="Scene" color="emerald" value={brief.scene} />
          </div>

          {/* Color Palette — full width */}
          <div className="bg-slate-800/50 border border-slate-700/40 rounded-md px-3 py-2.5">
            <div className="flex items-center gap-1.5 mb-2">
              <Palette className="w-3.5 h-3.5 text-rose-400" />
              <span className="text-[11px] font-semibold text-rose-300 uppercase tracking-wider">Color Palette</span>
            </div>
            <div className="flex flex-wrap gap-2">
              {brief.colorPalette.map((color, i) => (
                <ColorChip key={i} color={color} />
              ))}
            </div>
          </div>

          {/* Footer hint */}
          <p className="text-[11px] text-slate-500 text-center pt-1">
            <Zap className="w-3 h-3 inline mr-1 text-pink-500/70" />
            Copy this brief and paste it into Runway, Kling, Sora, or your video tool of choice.
          </p>
        </div>
      )}
    </div>
  );
}

function BriefField({
  icon,
  label,
  value,
  color,
}: {
  icon: React.ReactNode;
  label: string;
  value: string;
  color: "sky" | "amber" | "violet" | "emerald";
}) {
  const bgMap = {
    sky: "bg-sky-950/40 border-sky-800/30",
    amber: "bg-amber-950/40 border-amber-800/30",
    violet: "bg-violet-950/40 border-violet-800/30",
    emerald: "bg-emerald-950/40 border-emerald-800/30",
  };
  const labelMap = {
    sky: "text-sky-300",
    amber: "text-amber-300",
    violet: "text-violet-300",
    emerald: "text-emerald-300",
  };

  return (
    <div className={cn("rounded-md border px-3 py-2.5", bgMap[color])}>
      <div className="flex items-center gap-1.5 mb-1">
        {icon}
        <span className={cn("text-[11px] font-semibold uppercase tracking-wider", labelMap[color])}>{label}</span>
      </div>
      <p className="text-xs text-slate-200 leading-relaxed">{value}</p>
    </div>
  );
}

function ColorChip({ color }: { color: string }) {
  // Extract hex if present: "Burnt sienna (#8B4513)" → #8B4513
  const hexMatch = color.match(/#([0-9A-Fa-f]{3,6})/);
  const hex = hexMatch ? hexMatch[0] : null;
  const label = color.replace(/\s*\(#[0-9A-Fa-f]{3,6}\)/, "").trim();

  return (
    <div className="flex items-center gap-1.5 bg-slate-700/50 border border-slate-600/40 rounded-full px-2.5 py-1">
      {hex && (
        <div
          className="w-3 h-3 rounded-full border border-white/20 flex-shrink-0"
          style={{ backgroundColor: hex }}
        />
      )}
      <span className="text-xs text-slate-200">{label}</span>
    </div>
  );
}
